# Site settings
title: Bahrain
client:
  name: Bahrain
  link: 
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Der weltoffene Inselstaat im Arabischen Golf mit seiner 4.000 Jahre alten Geschichte schlummert völlig zu Unrecht im Schatten der großen arabischen Metropolen. Zwischen Souqs und Skyline lockt das Land der Perlenfischer zu Familienspaß und Nightlife, warten unberührte Traumstrände und ein einzigartiges Aktivitätsangebot von Motorsport bis Kunstgenuss.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/bahrain" # the subpath of your site, e.g. /blog/
img:     "/de/bahrain/_assets/img"
css:     "/de/bahrain/_assets/css"
js:      "/de/bahrain/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed